name: Build & Push Custom Frappe App Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Frappe Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout custom app repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME}}
          password: ${{ secrets.GH_TOKEN }}

      - name: Base64 encode app.json
        id: encode_apps_json
        run: |
          export APPS_JSON_BASE64=$(base64 -w 0 app.json)
          echo "APPS_JSON_BASE64=$APPS_JSON_BASE64" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
            --build-arg=FRAPPE_BRANCH=version-15 \
            --build-arg=APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }} \
            --tag=ghcr.io/mrjoyboy/frappe-custom:hms \
            --file=images/layered/Containerfile .

          docker push ghcr.io/mrjoyboy/frappe-custom:hms

  deploy:
    name: Deploy to ec2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker compose -f ${{secrets.COMPOSE_FILE}} pull
            docker compose -f ${{secrets.COMPOSE_FILE}} down && docker compose -f ${{secrets.COMPOSE_FILE}} up -d
            docker compose -f ${{secrets.COMPOSE_FILE}} exec backend bench --site ${{secrets.SITE}} migrate
            docker image prune
